// Copy for a center's public site (UZ/RU/EN). Only claims that are true
// for every center: no promised response times, free trials or titles.
export type SiteLang = "UZ" | "RU" | "EN";

const uz = {
  loading: "Sahifa yuklanmoqda...",
  notFoundTitle: "O'quv markazi topilmadi",
  notFoundText: "Manzil mavjud emas yoki noto'g'ri kiritilgan. Havolani tekshiring.",
  backHome: "Bosh sahifaga",
  navCourses: "Kurslar",
  navTeachers: "Ustozlar",
  navBranches: "Filiallar",
  navNews: "Yangiliklar",
  apply: "Ariza qoldirish",
  login: "Kirish",
  category: { TIL_MARKAZI: "Til markazi", MATEMATIKA: "Aniq fanlar markazi", IT: "IT va dasturlash", BOSHQA: "O'quv markazi" } as Record<string, string>,
  heroTitle: "{name} — bilim olish uchun qulay joy",
  heroDesc: "Kurslar, jadval va narxlar bilan tanishing, so'ng ariza qoldiring — markaz siz bilan bog'lanadi.",
  seeCourses: "Kurslarni ko'rish",
  slideTeacherTitle: "Ustoz bilan jonli dars",
  slideTeacherText: "Savol bering, mashq qiling, ustoz yonida o'rganing.",
  slideAiTitle: "AI yordamchi bilan mashq",
  slideAiText: "Qo'shimcha mashqlar va tushunarli izohlar — darsdan keyin ham.",
  slideResultsTitle: "Natijangizni kuzating",
  slideResultsText: "Baholar, davomat va test natijalari shaxsiy kabinetda.",
  slidePhoto: "Markazimizdan lavhalar",
  statGroups: "o'quv guruhi",
  statTeachers: "ustoz",
  statBranches: "filial",
  coursesLabel: "Kurslar",
  coursesTitle: "Mavjud o'quv guruhlari",
  all: "Barchasi",
  noCourses: "Hozircha bu yo'nalishda guruh yo'q.",
  days: "Kunlar",
  time: "Vaqt",
  teacher: "Ustoz",
  branch: "Filial",
  perMonth: "oyiga",
  priceOnRequest: "Narxi kelishiladi",
  enroll: "Yozilish",
  teachersLabel: "Ustozlar",
  teachersTitle: "Bizning ustozlarimiz",
  teacherFallback: "Ustoz",
  branchesLabel: "Filiallar",
  branchesTitle: "Bizni qayerdan topasiz",
  noAddress: "Manzil ko'rsatilmagan",
  openMap: "Xaritada ochish",
  newsLabel: "Yangiliklar",
  newsTitle: "Markaz yangiliklari",
  formLabel: "Ariza",
  formTitle: "Darsga yoziling",
  formDesc: "Ma'lumotlaringizni qoldiring — markaz ma'muriyati siz bilan bog'lanadi.",
  fullName: "Ism-familiyangiz",
  fullNamePh: "Masalan: Sardor Rustamov",
  phone: "Telefon raqamingiz",
  parentPhone: "Ota-ona telefoni (ixtiyoriy)",
  course: "Qiziqtirgan yo'nalish",
  general: "Umumiy",
  branchPick: "Qulay filial",
  mainBranch: "Asosiy bino",
  notes: "Izoh yoki qulay vaqt (ixtiyoriy)",
  notesPh: "Masalan: tushdan keyin yoki dam olish kunlari",
  consent: "Ma'lumotlarim men bilan bog'lanish uchun ishlatilishiga roziman.",
  privacy: "Maxfiylik siyosati",
  send: "Arizani yuborish",
  sending: "Yuborilmoqda...",
  errRequired: "Ism va to'g'ri telefon raqamini kiriting",
  errConsent: "Ma'lumotlardan foydalanishga rozilik bering",
  errTooMany: "Juda ko'p urinish. Bir daqiqadan so'ng qayta yuboring.",
  errGeneric: "Ariza yuborishda xatolik yuz berdi",
  successTitle: "Arizangiz qabul qilindi!",
  successText: "Markaz ma'muriyati ko'rsatilgan raqam orqali siz bilan bog'lanadi.",
  again: "Yana ariza qoldirish",
  poweredBy: "TalimCRM platformasida",
  aboutLabel: "Biz haqimizda",
  whyLabel: "Nega aynan biz",
  whyTitle: "Bizni tanlash uchun sabablar",
  resultsLabel: "Natijalar",
  resultsTitle: "O'quvchilarimiz natijalari",
  galleryLabel: "Rasmlar",
  galleryTitle: "Markazimiz ichidan",
  videoTitle: "Markaz haqida video",
  testimonialsLabel: "Fikrlar",
  testimonialsTitle: "O'quvchi va ota-onalar nima deydi",
  faqLabel: "Savollar",
  faqTitle: "Ko'p so'raladigan savollar",
  hours: "Ish vaqti",
  trialBadge: "Bepul sinov darsi",
  trialCta: "Sinov darsiga yozilish",
  placementTitle: "Darajangizni bepul aniqlang",
  placementDesc: "Onlayn testni topshiring — natijaga qarab sizga mos guruhni tavsiya qilamiz.",
  placementCta: "Testni boshlash",
  seatsLeft: "{n} ta joy qoldi",
  seatsFull: "Joy qolmagan",
  priceFrom: "Narxlar",
  subjectsCount: "yo'nalish",
  call: "Qo'ng'iroq",
  write: "Yozish",
  followUs: "Bizni kuzating",
  courseUnsure: "Hali bilmayman — maslahat kerak",
  faqPriceQ: "Kurslar narxi qancha?",
  faqPriceA: "Narxlar guruhga qarab oyiga {price} so'm. Har bir guruhning aniq narxi \"Kurslar\" bo'limida ko'rsatilgan.",
  faqTrialQ: "Sinov darsi bormi?",
  faqTrialA: "Ha: {trial}. Ariza qoldiring — qulay kun va vaqtni siz bilan kelishamiz.",
  faqLevelQ: "Darajamni qanday bilaman?",
  faqLevelTestA: "Saytdagi bepul onlayn testni topshiring: natijangizga qarab sizga mos guruhni tavsiya qilamiz.",
  faqLevelA: "Birinchi uchrashuvda ustoz darajangizni aniqlaydi va sizni mos guruhga joylashtiradi.",
  faqScheduleQ: "Darslar qachon bo'ladi?",
  faqScheduleA: "Har bir guruhning dars kunlari va vaqti \"Kurslar\" bo'limida yozilgan.",
  faqHoursA: "Markaz ish vaqti: {hours}.",
  faqWhereQ: "Markaz qayerda joylashgan?",
  faqHowQ: "Qanday yozilaman?",
  faqHowA: "Sahifa pastidagi arizani to'ldiring{phone} — ma'muriyat siz bilan bog'lanib, guruh va vaqtni kelishadi.",
  faqHowPhone: " yoki {phone} raqamiga qo'ng'iroq qiling",
  faqTeachersQ: "Darslarni kimlar o'tadi?",
  faqTeachersA: "Markazimizda {n} nafar ustoz dars beradi: {names}.",
};

type SiteText = typeof uz;

const ru: SiteText = {
  loading: "Загрузка страницы...",
  notFoundTitle: "Учебный центр не найден",
  notFoundText: "Адрес не существует или введён неверно. Проверьте ссылку.",
  backHome: "На главную",
  navCourses: "Курсы",
  navTeachers: "Преподаватели",
  navBranches: "Филиалы",
  navNews: "Новости",
  apply: "Оставить заявку",
  login: "Войти",
  category: { TIL_MARKAZI: "Языковой центр", MATEMATIKA: "Центр точных наук", IT: "IT и программирование", BOSHQA: "Учебный центр" },
  heroTitle: "{name} — удобное место для учёбы",
  heroDesc: "Посмотрите курсы, расписание и цены, затем оставьте заявку — центр свяжется с вами.",
  seeCourses: "Смотреть курсы",
  slideTeacherTitle: "Живые уроки с преподавателем",
  slideTeacherText: "Задавайте вопросы, практикуйтесь, учитесь рядом с преподавателем.",
  slideAiTitle: "Практика с AI-помощником",
  slideAiText: "Дополнительные задания и понятные объяснения — и после урока.",
  slideResultsTitle: "Следите за результатами",
  slideResultsText: "Оценки, посещаемость и результаты тестов в личном кабинете.",
  slidePhoto: "Кадры из нашего центра",
  statGroups: "учебных групп",
  statTeachers: "преподавателей",
  statBranches: "филиалов",
  coursesLabel: "Курсы",
  coursesTitle: "Действующие учебные группы",
  all: "Все",
  noCourses: "Пока нет групп по этому направлению.",
  days: "Дни",
  time: "Время",
  teacher: "Преподаватель",
  branch: "Филиал",
  perMonth: "в месяц",
  priceOnRequest: "Цена по договорённости",
  enroll: "Записаться",
  teachersLabel: "Преподаватели",
  teachersTitle: "Наши преподаватели",
  teacherFallback: "Преподаватель",
  branchesLabel: "Филиалы",
  branchesTitle: "Где нас найти",
  noAddress: "Адрес не указан",
  openMap: "Открыть на карте",
  newsLabel: "Новости",
  newsTitle: "Новости центра",
  formLabel: "Заявка",
  formTitle: "Запишитесь на занятия",
  formDesc: "Оставьте данные — администрация центра свяжется с вами.",
  fullName: "Имя и фамилия",
  fullNamePh: "Например: Сардор Рустамов",
  phone: "Ваш телефон",
  parentPhone: "Телефон родителя (необязательно)",
  course: "Интересующее направление",
  general: "Общее",
  branchPick: "Удобный филиал",
  mainBranch: "Главное здание",
  notes: "Комментарий или удобное время (необязательно)",
  notesPh: "Например: после обеда или по выходным",
  consent: "Согласен(на) на использование моих данных для связи со мной.",
  privacy: "Политика конфиденциальности",
  send: "Отправить заявку",
  sending: "Отправка...",
  errRequired: "Введите имя и корректный номер телефона",
  errConsent: "Дайте согласие на обработку данных",
  errTooMany: "Слишком много попыток. Повторите через минуту.",
  errGeneric: "Не удалось отправить заявку",
  successTitle: "Заявка принята!",
  successText: "Администрация центра свяжется с вами по указанному номеру.",
  again: "Оставить ещё заявку",
  poweredBy: "Работает на TalimCRM",
  aboutLabel: "О нас",
  whyLabel: "Почему мы",
  whyTitle: "Причины выбрать нас",
  resultsLabel: "Результаты",
  resultsTitle: "Результаты наших учеников",
  galleryLabel: "Фото",
  galleryTitle: "Внутри нашего центра",
  videoTitle: "Видео о центре",
  testimonialsLabel: "Отзывы",
  testimonialsTitle: "Что говорят ученики и родители",
  faqLabel: "Вопросы",
  faqTitle: "Частые вопросы",
  hours: "Часы работы",
  trialBadge: "Бесплатный пробный урок",
  trialCta: "Записаться на пробный урок",
  placementTitle: "Узнайте свой уровень бесплатно",
  placementDesc: "Пройдите онлайн-тест — по результату порекомендуем подходящую группу.",
  placementCta: "Начать тест",
  seatsLeft: "Осталось мест: {n}",
  seatsFull: "Мест нет",
  priceFrom: "Цены",
  subjectsCount: "направлений",
  call: "Позвонить",
  write: "Написать",
  followUs: "Мы в соцсетях",
  courseUnsure: "Пока не знаю — нужна консультация",
  faqPriceQ: "Сколько стоят курсы?",
  faqPriceA: "В зависимости от группы — {price} сум в месяц. Точная цена каждой группы указана в разделе «Курсы».",
  faqTrialQ: "Есть ли пробный урок?",
  faqTrialA: "Да: {trial}. Оставьте заявку — договоримся об удобном дне и времени.",
  faqLevelQ: "Как узнать свой уровень?",
  faqLevelTestA: "Пройдите бесплатный онлайн-тест на сайте: по результату порекомендуем подходящую группу.",
  faqLevelA: "На первой встрече преподаватель определит ваш уровень и подберёт группу.",
  faqScheduleQ: "Когда проходят занятия?",
  faqScheduleA: "Дни и время занятий каждой группы указаны в разделе «Курсы».",
  faqHoursA: "Часы работы центра: {hours}.",
  faqWhereQ: "Где находится центр?",
  faqHowQ: "Как записаться?",
  faqHowA: "Заполните заявку внизу страницы{phone} — администратор свяжется с вами и подберёт группу и время.",
  faqHowPhone: " или позвоните по номеру {phone}",
  faqTeachersQ: "Кто ведёт занятия?",
  faqTeachersA: "В центре преподают {n} преподавателей: {names}.",
};

const en: SiteText = {
  loading: "Loading...",
  notFoundTitle: "Learning center not found",
  notFoundText: "This address doesn't exist or was typed wrong. Check the link.",
  backHome: "Home",
  navCourses: "Courses",
  navTeachers: "Teachers",
  navBranches: "Branches",
  navNews: "News",
  apply: "Apply",
  login: "Log in",
  category: { TIL_MARKAZI: "Language center", MATEMATIKA: "Math & sciences", IT: "IT & coding", BOSHQA: "Learning center" },
  heroTitle: "{name} — a good place to learn",
  heroDesc: "See the courses, schedule and prices, then apply — the center will get in touch.",
  seeCourses: "See courses",
  slideTeacherTitle: "Live lessons with a teacher",
  slideTeacherText: "Ask questions, practise and learn right next to your teacher.",
  slideAiTitle: "Practice with an AI helper",
  slideAiText: "Extra exercises and clear explanations — even after class.",
  slideResultsTitle: "Track your progress",
  slideResultsText: "Grades, attendance and test results in your own account.",
  slidePhoto: "Moments from our center",
  statGroups: "groups",
  statTeachers: "teachers",
  statBranches: "branches",
  coursesLabel: "Courses",
  coursesTitle: "Current groups",
  all: "All",
  noCourses: "No groups in this subject yet.",
  days: "Days",
  time: "Time",
  teacher: "Teacher",
  branch: "Branch",
  perMonth: "per month",
  priceOnRequest: "Price on request",
  enroll: "Enroll",
  teachersLabel: "Teachers",
  teachersTitle: "Our teachers",
  teacherFallback: "Teacher",
  branchesLabel: "Branches",
  branchesTitle: "Where to find us",
  noAddress: "No address given",
  openMap: "Open map",
  newsLabel: "News",
  newsTitle: "Center news",
  formLabel: "Application",
  formTitle: "Sign up for classes",
  formDesc: "Leave your details — the center will contact you.",
  fullName: "Full name",
  fullNamePh: "e.g. Sardor Rustamov",
  phone: "Your phone",
  parentPhone: "Parent's phone (optional)",
  course: "Subject you're interested in",
  general: "General",
  branchPick: "Preferred branch",
  mainBranch: "Main building",
  notes: "Note or preferred time (optional)",
  notesPh: "e.g. afternoons or weekends",
  consent: "I agree that my details are used to contact me.",
  privacy: "Privacy policy",
  send: "Send application",
  sending: "Sending...",
  errRequired: "Enter your name and a valid phone number",
  errConsent: "Please agree to the use of your details",
  errTooMany: "Too many attempts. Try again in a minute.",
  errGeneric: "Could not send the application",
  successTitle: "Application received!",
  successText: "The center will contact you on the number you gave.",
  again: "Send another",
  poweredBy: "Powered by TalimCRM",
  aboutLabel: "About us",
  whyLabel: "Why us",
  whyTitle: "Reasons to choose us",
  resultsLabel: "Results",
  resultsTitle: "Our students' results",
  galleryLabel: "Photos",
  galleryTitle: "Inside our center",
  videoTitle: "Video about the center",
  testimonialsLabel: "Testimonials",
  testimonialsTitle: "What students and parents say",
  faqLabel: "Questions",
  faqTitle: "Frequently asked questions",
  hours: "Opening hours",
  trialBadge: "Free trial lesson",
  trialCta: "Book a trial lesson",
  placementTitle: "Check your level for free",
  placementDesc: "Take the online test — we'll suggest the right group from your result.",
  placementCta: "Start the test",
  seatsLeft: "{n} places left",
  seatsFull: "No places left",
  priceFrom: "Prices",
  subjectsCount: "subjects",
  call: "Call",
  write: "Message",
  followUs: "Follow us",
  courseUnsure: "Not sure yet — I need advice",
  faqPriceQ: "How much do the courses cost?",
  faqPriceA: "Depending on the group, {price} UZS per month. Each group's exact price is in the Courses section.",
  faqTrialQ: "Is there a trial lesson?",
  faqTrialA: "Yes: {trial}. Leave an application and we'll agree on a day and time.",
  faqLevelQ: "How do I find out my level?",
  faqLevelTestA: "Take the free online test on this site: we'll suggest the right group from your result.",
  faqLevelA: "At the first meeting a teacher checks your level and places you in the right group.",
  faqScheduleQ: "When are the lessons?",
  faqScheduleA: "Each group's days and times are listed in the Courses section.",
  faqHoursA: "Opening hours: {hours}.",
  faqWhereQ: "Where is the center?",
  faqHowQ: "How do I sign up?",
  faqHowA: "Fill in the application at the bottom of the page{phone} — the office will contact you to agree on a group and time.",
  faqHowPhone: " or call {phone}",
  faqTeachersQ: "Who teaches?",
  faqTeachersA: "{n} teachers work at the center: {names}.",
};

export const SITE_TEXT: Record<SiteLang, SiteText> = { UZ: uz, RU: ru, EN: en };
