// Copy for a center's public site (UZ/RU/EN). Only claims that are true
// for every center: no promised response times, free trials or titles.
export type SiteLang = "UZ" | "RU" | "EN";

const uz = {
  loading: "Sahifa yuklanmoqda...",
  notFoundTitle: "O'quv markazi topilmadi",
  notFoundText: "Manzil mavjud emas yoki noto'g'ri kiritilgan. Havolani tekshiring.",
  backHome: "Bosh sahifaga",
  navCourses: "Kurslar",
  navTeachers: "Ustozlar",
  navBranches: "Filiallar",
  navNews: "Yangiliklar",
  apply: "Ariza qoldirish",
  login: "Kirish",
  category: { TIL_MARKAZI: "Til markazi", MATEMATIKA: "Aniq fanlar markazi", IT: "IT va dasturlash", BOSHQA: "O'quv markazi" } as Record<string, string>,
  heroTitle: "{name} — bilim olish uchun qulay joy",
  heroDesc: "Kurslar, jadval va narxlar bilan tanishing, so'ng ariza qoldiring — markaz siz bilan bog'lanadi.",
  seeCourses: "Kurslarni ko'rish",
  statGroups: "o'quv guruhi",
  statTeachers: "ustoz",
  statBranches: "filial",
  coursesLabel: "Kurslar",
  coursesTitle: "Mavjud o'quv guruhlari",
  all: "Barchasi",
  noCourses: "Hozircha bu yo'nalishda guruh yo'q.",
  days: "Kunlar",
  time: "Vaqt",
  teacher: "Ustoz",
  branch: "Filial",
  perMonth: "oyiga",
  priceOnRequest: "Narxi kelishiladi",
  enroll: "Yozilish",
  teachersLabel: "Ustozlar",
  teachersTitle: "Bizning ustozlarimiz",
  teacherFallback: "Ustoz",
  branchesLabel: "Filiallar",
  branchesTitle: "Bizni qayerdan topasiz",
  noAddress: "Manzil ko'rsatilmagan",
  openMap: "Xaritada ochish",
  newsLabel: "Yangiliklar",
  newsTitle: "Markaz yangiliklari",
  formLabel: "Ariza",
  formTitle: "Darsga yoziling",
  formDesc: "Ma'lumotlaringizni qoldiring — markaz ma'muriyati siz bilan bog'lanadi.",
  fullName: "Ism-familiyangiz",
  fullNamePh: "Masalan: Sardor Rustamov",
  phone: "Telefon raqamingiz",
  parentPhone: "Ota-ona telefoni (ixtiyoriy)",
  course: "Qiziqtirgan yo'nalish",
  general: "Umumiy",
  branchPick: "Qulay filial",
  mainBranch: "Asosiy bino",
  notes: "Izoh yoki qulay vaqt (ixtiyoriy)",
  notesPh: "Masalan: tushdan keyin yoki dam olish kunlari",
  consent: "Ma'lumotlarim men bilan bog'lanish uchun ishlatilishiga roziman.",
  privacy: "Maxfiylik siyosati",
  send: "Arizani yuborish",
  sending: "Yuborilmoqda...",
  errRequired: "Ism va to'g'ri telefon raqamini kiriting",
  errConsent: "Ma'lumotlardan foydalanishga rozilik bering",
  errTooMany: "Juda ko'p urinish. Bir daqiqadan so'ng qayta yuboring.",
  errGeneric: "Ariza yuborishda xatolik yuz berdi",
  successTitle: "Arizangiz qabul qilindi!",
  successText: "Markaz ma'muriyati ko'rsatilgan raqam orqali siz bilan bog'lanadi.",
  again: "Yana ariza qoldirish",
  poweredBy: "TalimCRM platformasida",
};

type SiteText = typeof uz;

const ru: SiteText = {
  loading: "Загрузка страницы...",
  notFoundTitle: "Учебный центр не найден",
  notFoundText: "Адрес не существует или введён неверно. Проверьте ссылку.",
  backHome: "На главную",
  navCourses: "Курсы",
  navTeachers: "Преподаватели",
  navBranches: "Филиалы",
  navNews: "Новости",
  apply: "Оставить заявку",
  login: "Войти",
  category: { TIL_MARKAZI: "Языковой центр", MATEMATIKA: "Центр точных наук", IT: "IT и программирование", BOSHQA: "Учебный центр" },
  heroTitle: "{name} — удобное место для учёбы",
  heroDesc: "Посмотрите курсы, расписание и цены, затем оставьте заявку — центр свяжется с вами.",
  seeCourses: "Смотреть курсы",
  statGroups: "учебных групп",
  statTeachers: "преподавателей",
  statBranches: "филиалов",
  coursesLabel: "Курсы",
  coursesTitle: "Действующие учебные группы",
  all: "Все",
  noCourses: "Пока нет групп по этому направлению.",
  days: "Дни",
  time: "Время",
  teacher: "Преподаватель",
  branch: "Филиал",
  perMonth: "в месяц",
  priceOnRequest: "Цена по договорённости",
  enroll: "Записаться",
  teachersLabel: "Преподаватели",
  teachersTitle: "Наши преподаватели",
  teacherFallback: "Преподаватель",
  branchesLabel: "Филиалы",
  branchesTitle: "Где нас найти",
  noAddress: "Адрес не указан",
  openMap: "Открыть на карте",
  newsLabel: "Новости",
  newsTitle: "Новости центра",
  formLabel: "Заявка",
  formTitle: "Запишитесь на занятия",
  formDesc: "Оставьте данные — администрация центра свяжется с вами.",
  fullName: "Имя и фамилия",
  fullNamePh: "Например: Сардор Рустамов",
  phone: "Ваш телефон",
  parentPhone: "Телефон родителя (необязательно)",
  course: "Интересующее направление",
  general: "Общее",
  branchPick: "Удобный филиал",
  mainBranch: "Главное здание",
  notes: "Комментарий или удобное время (необязательно)",
  notesPh: "Например: после обеда или по выходным",
  consent: "Согласен(на) на использование моих данных для связи со мной.",
  privacy: "Политика конфиденциальности",
  send: "Отправить заявку",
  sending: "Отправка...",
  errRequired: "Введите имя и корректный номер телефона",
  errConsent: "Дайте согласие на обработку данных",
  errTooMany: "Слишком много попыток. Повторите через минуту.",
  errGeneric: "Не удалось отправить заявку",
  successTitle: "Заявка принята!",
  successText: "Администрация центра свяжется с вами по указанному номеру.",
  again: "Оставить ещё заявку",
  poweredBy: "Работает на TalimCRM",
};

const en: SiteText = {
  loading: "Loading...",
  notFoundTitle: "Learning center not found",
  notFoundText: "This address doesn't exist or was typed wrong. Check the link.",
  backHome: "Home",
  navCourses: "Courses",
  navTeachers: "Teachers",
  navBranches: "Branches",
  navNews: "News",
  apply: "Apply",
  login: "Log in",
  category: { TIL_MARKAZI: "Language center", MATEMATIKA: "Math & sciences", IT: "IT & coding", BOSHQA: "Learning center" },
  heroTitle: "{name} — a good place to learn",
  heroDesc: "See the courses, schedule and prices, then apply — the center will get in touch.",
  seeCourses: "See courses",
  statGroups: "groups",
  statTeachers: "teachers",
  statBranches: "branches",
  coursesLabel: "Courses",
  coursesTitle: "Current groups",
  all: "All",
  noCourses: "No groups in this subject yet.",
  days: "Days",
  time: "Time",
  teacher: "Teacher",
  branch: "Branch",
  perMonth: "per month",
  priceOnRequest: "Price on request",
  enroll: "Enroll",
  teachersLabel: "Teachers",
  teachersTitle: "Our teachers",
  teacherFallback: "Teacher",
  branchesLabel: "Branches",
  branchesTitle: "Where to find us",
  noAddress: "No address given",
  openMap: "Open map",
  newsLabel: "News",
  newsTitle: "Center news",
  formLabel: "Application",
  formTitle: "Sign up for classes",
  formDesc: "Leave your details — the center will contact you.",
  fullName: "Full name",
  fullNamePh: "e.g. Sardor Rustamov",
  phone: "Your phone",
  parentPhone: "Parent's phone (optional)",
  course: "Subject you're interested in",
  general: "General",
  branchPick: "Preferred branch",
  mainBranch: "Main building",
  notes: "Note or preferred time (optional)",
  notesPh: "e.g. afternoons or weekends",
  consent: "I agree that my details are used to contact me.",
  privacy: "Privacy policy",
  send: "Send application",
  sending: "Sending...",
  errRequired: "Enter your name and a valid phone number",
  errConsent: "Please agree to the use of your details",
  errTooMany: "Too many attempts. Try again in a minute.",
  errGeneric: "Could not send the application",
  successTitle: "Application received!",
  successText: "The center will contact you on the number you gave.",
  again: "Send another",
  poweredBy: "Powered by TalimCRM",
};

export const SITE_TEXT: Record<SiteLang, SiteText> = { UZ: uz, RU: ru, EN: en };
