import { diskStorage } from 'multer';
import { extname, join } from 'path';
import { createId } from '@paralleldrive/cuid2';

// Shared multer disk-storage config for homework/exam attachments —
// content-addressed-ish filenames (cuid) so nothing collides, original
// name is kept separately in the DB for display/download.
export const UPLOAD_DIR = join(__dirname, '..', '..', 'uploads');

export const attachmentStorage = diskStorage({
  destination: UPLOAD_DIR,
  filename: (_req, file, cb) => {
    cb(null, `${createId()}${extname(file.originalname)}`);
  },
});

export const ATTACHMENT_MAX_SIZE = 15 * 1024 * 1024; // 15MB

// Saves generated bytes (e.g. a PDF made from AI text) like an upload and
// returns the stored file name.
export async function saveGeneratedFile(bytes: Buffer, ext: string) {
  const { mkdir, writeFile } = await import('fs/promises');
  await mkdir(UPLOAD_DIR, { recursive: true });
  const name = `${createId()}${ext}`;
  await writeFile(join(UPLOAD_DIR, name), bytes);
  return name;
}
