// Landing page copy (from the original talimcrm-demo design), UZ/RU/EN.
export type LandingLang = "UZ" | "RU" | "EN";

const uz = {
  navFeatures: "Imkoniyatlar",
  navHow: "Qanday ishlaydi",
  navPricing: "Tariflar",
  login: "Kirish",
  start: "Bepul boshlash",
  badge: "O'quv markazlar uchun CRM",
  heroTitle: "Markazingizni boshqarish endi bitta joyda",
  heroDesc: "Jadval, davomat, to'lovlar va o'quvchilar — hammasi bitta tizimda. O'quvchi va ota-onalar uchun esa alohida shaxsiy bo'lim, o'z subdomeningiz bilan.",
  tryFree: "Bepul sinab ko'rish",
  demo: "Demo ko'rish",
  noCard: "7 kun bepul — karta talab qilinmaydi",
  todayLessons: "Bugungi darslar",
  online: "Onlayn",
  students: "o'quvchi",
  monthIncome: "Bu oy tushum",
  activeStudents: "Faol o'quvchi",
  lastPayments: "So'nggi to'lovlar",
  newCount: "3 ta yangi",
  paidToday: "Bugun tushgan",
  waiting: "Kutilmoqda",
  waitingCount: "7 ta",
  monthStats: "Oylik statistika",
  growth: "O'quvchilar o'sishi",
  avgAttendance: "O'rtacha davomat",
  som: "so'm",
  whoLabel: "Kimlar uchun mos",
  whoTitle: "Har xil turdagi o'quv markazlari uchun ishlaydi",
  who: [
    ["O'quv markazlari", "Til, matematika, IT yoki boshqa yo'nalishda — ko'plab guruh, daraja va filiallarni bitta tizimda boshqaring."],
    ["IT va dasturlash maktablari", "Kurs bosqichlari, loyihalar va bitiruvchilar portfolio holatini kuzatib boring."],
    ["Repetitorlik", "Guruh tuzmasdan — faqat o'qituvchi va o'quvchi juftligiga mos, yakka darslar uchun soddalashtirilgan jadval."],
    ["Musiqa va san'at maktablari", "Cholg'u asbobi yoki xonani bron qilish, har bir o'quvchi uchun individual narx va ota-onalarga oylik hisobot."],
  ],
  clients: "Bizning mijozlarimiz",
  featuresLabel: "Imkoniyatlar",
  featuresTitle: "Markazni boshqarish uchun kerakli hamma narsa",
  features: [
    ["Jadval va guruhlar", "Guruhlarni tuzing, o'quvchilarni taqsimlang, dars jadvalini bir zumda sozlang."],
    ["To'lov va abonement", "Click va Payme orqali to'lov, avtomatik qarzdorlik va muddat eslatmalari."],
    ["O'quvchi ilovasi", "O'quvchi va ota-onalar uchun jadval, davomat va to'lov holati bir joyda."],
    ["Hisobot va statistika", "Tushum, to'ldirilganlik va o'qituvchi samaradorligi — real vaqtda."],
  ],
  aiNew: "✨ Yangi",
  aiTitle: "Sun'iy intellekt endi markazingiz ichida ishlaydi",
  aiDesc: "Dars materiallarini yaratishdan tortib, qaysi o'quvchi ketib qolish xavfida ekanini oldindan aytib berishgacha — AI sizning o'rningizga o'ylaydi.",
  ai: [
    ["AI Materiallar", "Dars rejasi, uy vazifasi, test, IELTS/CEFR mock savollar va matematik masalalar bir necha soniyada tayyor."],
    ["AI tahlil va tavsiyalar", "Kim ketib qolish xavfida, qaysi guruh foyda keltirmayapti — AI o'zi tahlil qilib, aniq harakat tavsiya qiladi."],
    ["O'quvchi uchun AI Yordamchi", "O'quvchi tushunmagan mavzuni Telegram orqali AI'dan so'raydi — tunu kun, o'qituvchini band qilmasdan."],
  ],
  howLabel: "Qanday ishlaydi",
  howTitle: "3 qadamda ishga tushiring",
  how: [
    ["Ro'yxatdan o'ting", "Tarif tanlang, markaz nomini kiriting — sizga darhol shaxsiy subdomen beriladi."],
    ["Guruhlaringizni sozlang", "O'qituvchi, guruh va dars jadvalini qo'shing — bir necha daqiqada tayyor."],
    ["O'quvchilarni taklif qiling", "Ular Telegram orqali shaxsiy kabinetiga kirib, jadval va to'lovni ko'radi."],
  ],
  welcome: "Xush kelibsiz,",
  nextLesson: "Keyingi dars",
  nextLessonValue: "IELTS Speaking — Bugun, 14:00",
  attendance: "Davomat",
  attendanceValue: "18/20 dars",
  paymentStatus: "To'lov holati",
  paidUntil: "To'langan — dekabrgacha",
  aiHelper: "AI Yordamchi",
  chat: ["Present Perfect qachon ishlatiladi?", "Misol bilan tushuntiraman: \"I have visited Paris\" — tajriba haqida gapirganda ishlatiladi 😊", "Rahmat! Mashqlar ham bera olasizmi?"],
  homework: "Uy vazifalari",
  hw: ["Present Perfect mashqlari", "Muddat: bugun, 23:59", "Reading — matn", "Bajarildi", "Speaking — audio yozish", "Muddat: ertaga"],
  portalLabel: "O'quvchilar uchun",
  portalTitle: "O'quvchi va ota-onalar uchun alohida bo'lim",
  portalDesc: "Telegram orqali ochiladigan shaxsiy kabinetda o'quvchi darslar jadvalini, uy vazifalarini, davomatini, to'lov holatini ko'radi va tushunmagan mavzuda to'g'ridan-to'g'ri AI Yordamchidan so'raydi — qo'ng'iroq qilib so'rashning hojati yo'q.",
  whyLabel: "Nega TalimCRM?",
  whyTitle: "Ishonch bilan ishlash uchun to'rtta sabab",
  why: [
    ["Ma'lumotlaringiz xavfsiz", "Har bir markazning ma'lumoti alohida ajratilgan va shifrlangan holda saqlanadi — boshqa mijoz uni ko'ra olmaydi."],
    ["O'zbek tilida tezkor yordam", "Savolingiz bo'lsa, Telegram orqali to'g'ridan-to'g'ri jonli qo'llab-quvvatlash xizmatiga yozasiz."],
    ["Bepul ko'chirib berish", "Excel yoki qog'ozdagi mavjud o'quvchi ro'yxatingizni bepul CRM'ga o'tkazib beramiz."],
    ["Xohlagan payt bekor qiling", "Uzoq muddatli shartnoma yo'q — oylik obuna, istalgan vaqtda to'xtatishingiz mumkin."],
  ],
  faqLabel: "Savollar",
  faqTitle: "Ko'p so'raladigan savollar",
  faq: [
    ["Mavjud Excel jadvalimni ko'chirib bera olasizmi?", "Ha. Ro'yxatdan o'tganingizdan so'ng jamoamiz o'quvchilar, guruhlar va to'lov tarixini bepul o'tkazib beradi."],
    ["To'lov qanday amalga oshadi?", "Click yoki Payme orqali oylik avtomatik to'lov. Kartangiz saqlanmaydi — to'lov to'g'ridan-to'g'ri to'lov tizimida amalga oshadi."],
    ["Tarifni keyinroq o'zgartirsam bo'ladimi?", "Ha, istalgan vaqtda kattaroq yoki kichikroq tarifga o'tishingiz mumkin, ma'lumotlaringiz saqlanib qoladi."],
    ["Uzoq muddatli shartnoma imzolash kerakmi?", "Yo'q — oylik obuna, xohlagan vaqtingizda bekor qilishingiz mumkin."],
  ],
  pricingLabel: "Tariflar",
  pricingTitle: "Markazingiz hajmiga mos tarifni tanlang",
  perMonth: " so'm/oy",
  popular: "Eng mashhur",
  choose: "Tanlash",
  contact: "Aloqaga chiqish",
  individual: "Individual",
  plans: [
    ["1–2 filial, 150 tagacha o'quvchi", "Jadval va davomat", "To'lov kuzatuvi", "1 admin akkaunt"],
    ["3–5 filial, 600 tagacha o'quvchi", "Basic'dagi hammasi", "Telegram bildirishnoma", "Hisobot va statistika", "5 admin akkaunt"],
    ["Ko'p filialli tarmoqlar uchun", "Pro'dagi hammasi", "Cheksiz o'quvchi", "Maxsus integratsiyalar"],
  ],
  ctaTitle: "Bugun bepul boshlang",
  ctaDesc: "7 kun bepul sinov, karta talab qilinmaydi.",
  register: "Ro'yxatdan o'tish",
  footerContact: "Foydalanish shartlari",
  privacy: "Maxfiylik siyosati",
};

type LandingText = typeof uz;

const ru: LandingText = {
  navFeatures: "Возможности",
  navHow: "Как это работает",
  navPricing: "Тарифы",
  login: "Войти",
  start: "Начать бесплатно",
  badge: "CRM для учебных центров",
  heroTitle: "Управляйте центром в одном месте",
  heroDesc: "Расписание, посещаемость, оплаты и ученики — всё в одной системе. А для учеников и родителей — отдельный личный кабинет на вашем поддомене.",
  tryFree: "Попробовать бесплатно",
  demo: "Посмотреть демо",
  noCard: "7 дней бесплатно — карта не нужна",
  todayLessons: "Уроки сегодня",
  online: "Онлайн",
  students: "учеников",
  monthIncome: "Доход за месяц",
  activeStudents: "Активных учеников",
  lastPayments: "Последние оплаты",
  newCount: "3 новых",
  paidToday: "Поступило сегодня",
  waiting: "Ожидается",
  waitingCount: "7",
  monthStats: "Статистика за месяц",
  growth: "Рост учеников",
  avgAttendance: "Средняя посещаемость",
  som: "сум",
  whoLabel: "Кому подходит",
  whoTitle: "Работает для любых учебных центров",
  who: [
    ["Учебные центры", "Языки, математика, IT или другое направление — много групп, уровней и филиалов в одной системе."],
    ["IT и школы программирования", "Следите за этапами курса, проектами и портфолио выпускников."],
    ["Репетиторство", "Без групп — упрощённое расписание для индивидуальных занятий учителя и ученика."],
    ["Музыкальные и художественные школы", "Бронь инструмента или класса, индивидуальная цена и ежемесячный отчёт родителям."],
  ],
  clients: "Наши клиенты",
  featuresLabel: "Возможности",
  featuresTitle: "Всё, что нужно для управления центром",
  features: [
    ["Расписание и группы", "Создавайте группы, распределяйте учеников и настраивайте расписание за минуту."],
    ["Оплата и абонементы", "Оплата через Click и Payme, автоматический учёт долгов и напоминания о сроках."],
    ["Приложение ученика", "Расписание, посещаемость и статус оплаты для учеников и родителей в одном месте."],
    ["Отчёты и статистика", "Доход, заполняемость и эффективность учителей — в реальном времени."],
  ],
  aiNew: "✨ Новое",
  aiTitle: "Искусственный интеллект теперь работает внутри вашего центра",
  aiDesc: "От создания учебных материалов до прогноза, какой ученик может уйти, — ИИ думает за вас.",
  ai: [
    ["ИИ-материалы", "План урока, домашнее задание, тест, mock-вопросы IELTS/CEFR и задачи по математике — за несколько секунд."],
    ["ИИ-анализ и рекомендации", "Кто может уйти, какая группа не приносит прибыль — ИИ анализирует и советует конкретные действия."],
    ["ИИ-помощник для ученика", "Ученик спрашивает непонятную тему у ИИ в Telegram — круглосуточно, не отвлекая учителя."],
  ],
  howLabel: "Как это работает",
  howTitle: "Запуск за 3 шага",
  how: [
    ["Зарегистрируйтесь", "Выберите тариф, введите название центра — сразу получите свой поддомен."],
    ["Настройте группы", "Добавьте учителей, группы и расписание — всё готово за несколько минут."],
    ["Пригласите учеников", "Они входят в личный кабинет через Telegram и видят расписание и оплаты."],
  ],
  welcome: "Добро пожаловать,",
  nextLesson: "Следующий урок",
  nextLessonValue: "IELTS Speaking — сегодня, 14:00",
  attendance: "Посещаемость",
  attendanceValue: "18/20 уроков",
  paymentStatus: "Статус оплаты",
  paidUntil: "Оплачено — до декабря",
  aiHelper: "ИИ-помощник",
  chat: ["Когда используется Present Perfect?", "Объясню на примере: \"I have visited Paris\" — когда говорим об опыте 😊", "Спасибо! А упражнения можете дать?"],
  homework: "Домашние задания",
  hw: ["Упражнения на Present Perfect", "Срок: сегодня, 23:59", "Reading — текст", "Сделано", "Speaking — аудиозапись", "Срок: завтра"],
  portalLabel: "Для учеников",
  portalTitle: "Отдельный кабинет для учеников и родителей",
  portalDesc: "В личном кабинете через Telegram ученик видит расписание, домашние задания, посещаемость и статус оплаты, а непонятную тему спрашивает прямо у ИИ-помощника — звонить не нужно.",
  whyLabel: "Почему TalimCRM?",
  whyTitle: "Четыре причины работать уверенно",
  why: [
    ["Данные в безопасности", "Данные каждого центра хранятся отдельно и в зашифрованном виде — другие клиенты их не видят."],
    ["Быстрая поддержка", "Есть вопрос — пишите в живую поддержку прямо в Telegram."],
    ["Бесплатный перенос", "Бесплатно перенесём ваш список учеников из Excel или с бумаги в CRM."],
    ["Отмена в любой момент", "Без долгосрочного договора — помесячная подписка, остановить можно когда угодно."],
  ],
  faqLabel: "Вопросы",
  faqTitle: "Частые вопросы",
  faq: [
    ["Перенесёте мою таблицу Excel?", "Да. После регистрации наша команда бесплатно перенесёт учеников, группы и историю оплат."],
    ["Как происходит оплата?", "Ежемесячная автоматическая оплата через Click или Payme. Карта не сохраняется — оплата проходит в платёжной системе."],
    ["Можно потом сменить тариф?", "Да, в любое время можно перейти на больший или меньший тариф, данные сохранятся."],
    ["Нужно подписывать долгосрочный договор?", "Нет — помесячная подписка, отменить можно в любое время."],
  ],
  pricingLabel: "Тарифы",
  pricingTitle: "Выберите тариф под размер центра",
  perMonth: " сум/мес",
  popular: "Популярный",
  choose: "Выбрать",
  contact: "Связаться",
  individual: "Индивидуально",
  plans: [
    ["1–2 филиала, до 150 учеников", "Расписание и посещаемость", "Учёт оплат", "1 админ-аккаунт"],
    ["3–5 филиалов, до 600 учеников", "Всё из Basic", "Уведомления в Telegram", "Отчёты и статистика", "5 админ-аккаунтов"],
    ["Для сетей с многими филиалами", "Всё из Pro", "Без лимита учеников", "Особые интеграции"],
  ],
  ctaTitle: "Начните бесплатно сегодня",
  ctaDesc: "7 дней бесплатно, карта не нужна.",
  register: "Зарегистрироваться",
  footerContact: "Условия использования",
  privacy: "Политика конфиденциальности",
};

const en: LandingText = {
  navFeatures: "Features",
  navHow: "How it works",
  navPricing: "Pricing",
  login: "Log in",
  start: "Start free",
  badge: "CRM for learning centers",
  heroTitle: "Run your whole center from one place",
  heroDesc: "Schedule, attendance, payments and students — all in one system. Plus a separate personal space for students and parents, on your own subdomain.",
  tryFree: "Try it free",
  demo: "See the demo",
  noCard: "7 days free — no card required",
  todayLessons: "Today's lessons",
  online: "Online",
  students: "students",
  monthIncome: "Income this month",
  activeStudents: "Active students",
  lastPayments: "Latest payments",
  newCount: "3 new",
  paidToday: "Received today",
  waiting: "Pending",
  waitingCount: "7",
  monthStats: "Monthly stats",
  growth: "Student growth",
  avgAttendance: "Average attendance",
  som: "UZS",
  whoLabel: "Who it's for",
  whoTitle: "Works for every kind of learning center",
  who: [
    ["Learning centers", "Languages, math, IT or anything else — many groups, levels and branches in one system."],
    ["IT and coding schools", "Track course stages, projects and graduates' portfolios."],
    ["Tutoring", "No groups needed — a simple schedule for one-to-one lessons."],
    ["Music and art schools", "Book an instrument or room, set individual prices and send parents a monthly report."],
  ],
  clients: "Our clients",
  featuresLabel: "Features",
  featuresTitle: "Everything you need to run a center",
  features: [
    ["Schedule and groups", "Create groups, place students and set up the timetable in minutes."],
    ["Payments and plans", "Pay with Click and Payme, automatic debt tracking and due-date reminders."],
    ["Student app", "Schedule, attendance and payment status for students and parents in one place."],
    ["Reports and analytics", "Income, occupancy and teacher performance — in real time."],
  ],
  aiNew: "✨ New",
  aiTitle: "AI now works inside your center",
  aiDesc: "From creating lesson materials to warning you which student may leave — AI does the thinking for you.",
  ai: [
    ["AI materials", "Lesson plans, homework, tests, IELTS/CEFR mock questions and math problems in seconds."],
    ["AI insights", "Who may leave, which group isn't profitable — AI analyses and suggests clear actions."],
    ["AI helper for students", "Students ask AI about topics they missed on Telegram — day and night, without taking the teacher's time."],
  ],
  howLabel: "How it works",
  howTitle: "Get started in 3 steps",
  how: [
    ["Sign up", "Pick a plan, enter your center's name — you get your own subdomain right away."],
    ["Set up your groups", "Add teachers, groups and the timetable — ready in minutes."],
    ["Invite your students", "They open their personal space through Telegram and see schedule and payments."],
  ],
  welcome: "Welcome,",
  nextLesson: "Next lesson",
  nextLessonValue: "IELTS Speaking — Today, 14:00",
  attendance: "Attendance",
  attendanceValue: "18/20 lessons",
  paymentStatus: "Payment status",
  paidUntil: "Paid — until December",
  aiHelper: "AI helper",
  chat: ["When do we use Present Perfect?", "Here's an example: \"I have visited Paris\" — we use it to talk about experience 😊", "Thanks! Can you give me some exercises?"],
  homework: "Homework",
  hw: ["Present Perfect exercises", "Due: today, 23:59", "Reading — text", "Done", "Speaking — audio recording", "Due: tomorrow"],
  portalLabel: "For students",
  portalTitle: "A separate space for students and parents",
  portalDesc: "In a personal space opened through Telegram, students see their schedule, homework, attendance and payment status, and ask the AI helper directly about anything unclear — no phone calls needed.",
  whyLabel: "Why TalimCRM?",
  whyTitle: "Four reasons to work with confidence",
  why: [
    ["Your data is safe", "Each center's data is kept separate and encrypted — no other client can see it."],
    ["Fast support in your language", "Have a question? Write to live support directly on Telegram."],
    ["Free migration", "We move your existing student list from Excel or paper into the CRM for free."],
    ["Cancel any time", "No long-term contract — a monthly subscription you can stop whenever you like."],
  ],
  faqLabel: "Questions",
  faqTitle: "Frequently asked questions",
  faq: [
    ["Can you import my existing Excel sheet?", "Yes. After you sign up, our team moves your students, groups and payment history for free."],
    ["How does payment work?", "Monthly automatic payment via Click or Payme. Your card isn't stored — the payment happens in the payment system."],
    ["Can I change my plan later?", "Yes, move to a bigger or smaller plan any time; your data stays."],
    ["Do I need to sign a long-term contract?", "No — it's a monthly subscription you can cancel whenever you want."],
  ],
  pricingLabel: "Pricing",
  pricingTitle: "Choose a plan that fits your center",
  perMonth: " UZS/mo",
  popular: "Most popular",
  choose: "Choose",
  contact: "Contact us",
  individual: "Custom",
  plans: [
    ["1–2 branches, up to 150 students", "Schedule and attendance", "Payment tracking", "1 admin account"],
    ["3–5 branches, up to 600 students", "Everything in Basic", "Telegram notifications", "Reports and analytics", "5 admin accounts"],
    ["For multi-branch networks", "Everything in Pro", "Unlimited students", "Custom integrations"],
  ],
  ctaTitle: "Start free today",
  ctaDesc: "7-day free trial, no card required.",
  register: "Sign up",
  footerContact: "Terms of use",
  privacy: "Privacy policy",
};

export const LANDING_TEXT: Record<LandingLang, LandingText> = { UZ: uz, RU: ru, EN: en };
